name: CI
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  merge_group:
    types:
      - checks_requested

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Setup
        uses: ./.github/actions/setup

      - name: Lint files
        run: yarn lint

      - name: Typecheck files
        run: yarn typecheck

  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Setup
        uses: ./.github/actions/setup

      - name: Run unit tests
        run: yarn test --runInBand

  build-library:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Setup
        uses: ./.github/actions/setup

      - name: Build package
        run: yarn prepare

  build-android:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        example:
          - name: React Navigation
            path: examples/react-navigation
            gradle-wrapper: examples/react-navigation/android/gradle/wrapper/gradle-wrapper.properties
          - name: Expo Router
            path: examples/expo-router
            gradle-wrapper: examples/expo-router/android/gradle/wrapper/gradle-wrapper.properties

    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Setup
        uses: ./.github/actions/setup

      - name: Generate Expo Router Android project
        if: matrix.example.path == 'examples/expo-router'
        working-directory: ${{ matrix.example.path }}
        run: yarn exec expo prebuild --platform android --no-install

      - name: Install JDK
        uses: actions/setup-java@de7274f081f381c8f8158605e0321c36c376e2e6 # v6.0.1
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Finalize Android SDK
        run: |
          /bin/bash -c "yes | $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager --licenses > /dev/null"

      - name: Cache Gradle
        uses: actions/cache@55cc8345863c7cc4c66a329aec7e433d2d1c52a9 # v6.1.0
        with:
          path: |
            ~/.gradle/wrapper
            ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles(matrix.example.gradle-wrapper) }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Build ${{ matrix.example.name }} example for Android
        working-directory: ${{ matrix.example.path }}
        env:
          JAVA_OPTS: '-XX:MaxHeapSize=6g'
        run: yarn build:android

  build-ios:
    runs-on: macos-latest
    strategy:
      fail-fast: false
      matrix:
        example:
          - name: React Navigation
            path: examples/react-navigation
          - name: Expo Router
            path: examples/expo-router

    env:
      XCODE_VERSION: 26
      RCT_USE_RN_DEP: 1
      RCT_USE_PREBUILT_RNCORE: 1

    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Setup
        uses: ./.github/actions/setup

      - name: Use appropriate Xcode version
        uses: maxim-lobanov/setup-xcode@ed7a3b1fda3918c0306d1b724322adc0b8cc0a90 # v1.7.0
        with:
          xcode-version: ${{ env.XCODE_VERSION }}

      - name: Generate Expo Router iOS project
        if: matrix.example.path == 'examples/expo-router'
        working-directory: ${{ matrix.example.path }}
        run: yarn exec expo prebuild --platform ios --no-install

      - name: Install CocoaPods for ${{ matrix.example.name }} example
        working-directory: ${{ matrix.example.path }}
        run: |
          if [[ -f Gemfile ]]; then
            bundle install
            bundle exec pod install --repo-update --project-directory=ios
          else
            pod install --repo-update --project-directory=ios
          fi

      - name: Build ${{ matrix.example.name }} example for iOS
        working-directory: ${{ matrix.example.path }}
        run: yarn build:ios
